services:
  db:
    image: postgres
    network_mode: bridge
    user: postgres

    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=hpfolio
      - POSTGRES_USER=heidless
      - POSTGRES_PASSWORD=havana11
  web:
    network_mode: bridge
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=hpfolio
      - POSTGRES_USER=heidless
      - POSTGRES_PASSWORD=havana11
    depends_on:
      - db